# Generated by Django 2.0.3 on 2018-03-19 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employeepersonal',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(blank=True, default='', max_length=100)),
                ('lastname', models.CharField(blank=True, default='', max_length=100)),
                ('email', models.EmailField(blank=True, max_length=100, null=True, unique=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=100)),
                ('dateofbirth', models.DateField(max_length=12)),
                ('address1', models.CharField(max_length=1024)),
                ('address2', models.CharField(max_length=1024)),
                ('city', models.CharField(max_length=1024)),
                ('state', models.CharField(max_length=1024)),
                ('country', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=12)),
                ('phonenumber', models.IntegerField()),
            ],
            options={
                'db_table': 'employeepersonal',
            },
        ),
    ]
