# Generated by Django 2.0.3 on 2018-03-19 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employeejobdetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('copy_existing_details', models.CharField(blank=True, default='', max_length=100)),
                ('company', models.CharField(blank=True, default='', max_length=100)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('jobrole', models.CharField(blank=True, max_length=100)),
                ('reports_to', models.CharField(blank=True, max_length=100)),
                ('start_date', models.DateField(max_length=12)),
                ('ni_number', models.CharField(blank=True, max_length=1024)),
                ('holiday_year', models.CharField(blank=True, max_length=1024)),
                ('work_pattern', models.CharField(max_length=1024)),
                ('contracted_hours', models.FloatField()),
                ('full_time_hours', models.FloatField()),
                ('measured_in', models.CharField(max_length=100)),
                ('holidays_this_year', models.FloatField()),
                ('holidays_next_year', models.FloatField()),
                ('salary', models.FloatField()),
                ('salary_type', models.FloatField()),
                ('salary_currency', models.CharField(max_length=100)),
                ('employee_id', models.ForeignKey(db_column='employee_id', on_delete=django.db.models.deletion.DO_NOTHING, to='core.Employeepersonal')),
            ],
            options={
                'db_table': 'employeejobdetails',
            },
        ),
    ]
