# Generated by Django 2.0.3 on 2018-03-21 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_employeetask_snippet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('department', models.TextField()),
                ('degree', models.TextField()),
                ('phonenumber', models.IntegerField()),
                ('college', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'demo',
            },
        ),
    ]
