# Generated by Django 2.0.3 on 2018-05-03 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('plan', models.CharField(blank=True, choices=[('free_trial', 'Free_Trial'), ('monthly_plan', 'Monthly_Plan'), ('yearly_plan', 'Yearly_Plan')], default='', max_length=200)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=19)),
            ],
            options={
                'db_table': 'plans',
            },
        ),
    ]
