# Generated by Django 2.0.3 on 2018-05-07 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_companyprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
