# Generated by Django 2.0.3 on 2018-05-11 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0004_cartdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('expiration_date', models.DateTimeField()),
                ('subscription_plan', models.CharField(blank=True, max_length=100)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=19)),
                ('status', models.CharField(blank=True, choices=[('Y', 'active'), ('N', 'inactive')], max_length=200)),
                ('quantity', models.IntegerField(blank=True)),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subscription.CompanyProfile')),
            ],
            options={
                'db_table': 'company_subscription',
            },
        ),
    ]
