# Generated by Django 2.0.3 on 2018-05-11 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0005_companysubscription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companysubscription',
            old_name='user_id',
            new_name='user',
        ),
    ]
